"""initial schema

Revision ID: 1085fdfcc518
Revises: 
Create Date: 2026-04-29 03:13:42.293334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1085fdfcc518'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_asset_identifier'), 'analysis_results', ['asset_identifier'], unique=False)
    op.create_table('bcb_rate_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcb_rate_history_rate_date'), 'bcb_rate_history', ['rate_date'], unique=False)
    op.create_table('fixed_income_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('asset_subtype', sa.String(length=20), nullable=False),
    sa.Column('invested_amount', sa.Numeric(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('rate_value', sa.Numeric(), nullable=False),
    sa.Column('current_estimated_value', sa.Numeric(), nullable=True),
    sa.Column('is_tax_exempt', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_identifier'), 'market_snapshots', ['identifier'], unique=False)
    op.create_index(op.f('ix_market_snapshots_timestamp'), 'market_snapshots', ['timestamp'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('asset_subtype', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('avg_price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_positions_ticker'), 'stock_positions', ['ticker'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_stock_positions_ticker'), table_name='stock_positions')
    op.drop_table('stock_positions')
    op.drop_table('reports')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_market_snapshots_timestamp'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_identifier'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_table('fixed_income_positions')
    op.drop_index(op.f('ix_bcb_rate_history_rate_date'), table_name='bcb_rate_history')
    op.drop_table('bcb_rate_history')
    op.drop_index(op.f('ix_analysis_results_asset_identifier'), table_name='analysis_results')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
